# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pennapps-xvi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pennapps-xvi
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'pennapps-xviTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
